version: '3.7'

services:

  test-energo:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./.env
